import { Injectable, computed, signal } from '@angular/core';
import { toObservable } from '@angular/core/rxjs-interop';

type SupportedLanguage = 'en' | 'pl';

@Injectable({ providedIn: 'root' })
export class TranslateService {
  private readonly languageSignal = signal<SupportedLanguage>('pl');

  private readonly translations: Record<SupportedLanguage, Record<string, string>> =
    {
      en: {
        'home.title': 'World at War: Turn-Based Strategy',
        'home.subtitle': 'Compete against the AI or challenge other players in real time',
        'home.status.guest': 'Guest session',
        'home.status.registered': 'Welcome back',
        'home.banner.caption': 'Continue your ongoing battle',
        'home.banner.gameType.vsBot': 'Game vs AI',
        'home.banner.gameType.pvp': 'PvP Match',
        'home.banner.difficulty.easy': 'Novice',
        'home.banner.difficulty.medium': 'Expert',
        'home.banner.difficulty.hard': 'Master',
        'home.banner.status.waiting': 'Waiting',
        'home.banner.status.inProgress': 'In progress',
        'home.banner.status.finished': 'Finished',
        'home.banner.status.abandoned': 'Abandoned',
        'home.banner.status.draw': 'Draw',
        'home.banner.lastActivity': 'Last activity',
        'home.banner.boardSize': 'Board size',
        'home.banner.moves': 'Number of moves',
        'home.banner.continue': 'Continue game',
        'home.hero.cta.matchmaking': 'Start PvP matchmaking',
        'home.hero.cta.bot': 'Battle the AI',
        'home.stats.points': 'Total points',
        'home.stats.played': 'Games played',
        'home.stats.won': 'Games won',
        'home.menu.game': 'Game',
        'home.menu.matchmaking': 'Lobby',
        'home.menu.ranking': 'Leaderboard',
        'home.menu.login': 'Log in',
        'home.menu.theme': 'Theme',
        'home.menu.language': 'Language',
        'settings.audio.open': 'Audio settings',
        'settings.audio.title': 'Audio settings',
        'settings.audio.music': 'Background music',
        'settings.audio.musicDescription': 'Play ambient soundtrack during your matches.',
        'settings.audio.clickSound': 'Button clicks',
        'settings.audio.clickSoundDescription': 'Play a subtle sound whenever you interact with buttons.',
        'settings.audio.enabled': 'On',
        'settings.audio.disabled': 'Off',
        'home.gameModes.sectionTitle': 'Choose your mission',
        'home.gameModes.sectionSubtitle':
          'Select how you want to begin: quick skirmish, strategic AI duel, or real-time PvP.',
        'home.gameModes.guest.title': 'Play as guest',
        'home.gameModes.guest.description':
          'Create an instant guest session and jump into the action without signing up.',
        'home.gameModes.bot.title': 'Battle the AI',
        'home.gameModes.bot.description':
          'Train your tactics against adaptive AI opponents across multiple difficulties.',
        'home.gameModes.pvp.title': 'PvP matchmaking',
        'home.gameModes.pvp.description':
          'Enter the global queue and fight real commanders in ranked matches.',
        'home.gameModes.access.available': 'Available',
        'home.gameModes.access.unavailable': 'Unavailable',
        'home.gameModes.select': 'Select',
        'home.gameModes.selectAria': 'Select game mode',
        'home.authSection.title': 'Track every victory',
        'home.authSection.description':
          'Create an account to save progress, earn ranking points, and unlock advanced features.',
        'home.authSection.login': 'Log in',
        'home.authSection.register': 'Register',
        'home.error.title': 'Something went wrong',
        'home.error.guestSession': 'We could not create a guest session. Please try again in a moment.',
        'home.error.navigation': 'Unable to navigate to the selected screen.',
        'home.error.savedGame': 'We could not load your last game. You can still start a new one.',
        'home.error.connection': 'Unable to connect to the server. Please check if the backend is running and try again.',
        'home.hero.title': 'Start your mission',
        'home.hero.description': 'Choose how to play: quick guest session or full account with progress tracking.',
        'home.hero.title.loggedIn': 'Welcome back',
        'home.hero.description.loggedIn': 'Start a new game or continue your ongoing battle.',
        'home.hero.guestButton': 'Play as guest',
        'home.hero.loginButton': 'Log in and play',
        'home.hero.registerButton': 'Create new account',
        'home.hero.newGameButton': 'New game',
        'home.hero.continueGameButton': 'Continue game',
        'home.hero.logoutButton': 'Log out',
        'home.gameOptions.title': 'Choose game options',
        'home.gameOptions.modeTitle': 'Game mode',
        'home.gameOptions.boardSizeTitle': 'Board size',
        'home.gameOptions.cancel': 'Cancel',
        'home.gameOptions.start': 'Start game',
        'home.gameMode.easy': 'vs Novice',
        'home.gameMode.medium': 'vs Expert',
        'home.gameMode.hard': 'vs Master',
        'home.gameMode.pvp': 'PvP',
        'home.boardSize.3x3': '3x3',
        'home.boardSize.4x4': '4x4',
        'home.boardSize.5x5': '5x5',
        'game.title.bot': 'Game vs Bot',
        'game.title.pvp': 'PvP Game',
        'game.action.surrender': 'Surrender',
        'game.meta.status': 'Status',
        'game.meta.turn': 'Turn',
        'game.meta.time': 'Time',
        'game.info.type': 'Type',
        'game.info.opponent': 'Opponent',
        'game.info.status': 'Status',
        'game.info.currentPlayer': 'Current Player',
        'game.info.moves': 'Moves',
        'game.type.bot': 'vs Bot',
        'game.type.pvp': 'PvP',
        'game.pvp.points': 'Points at stake',
        'game.status.waiting': 'Waiting',
        'game.status.in_progress': 'In Progress',
        'game.status.finished': 'Finished',
        'game.status.draw': 'Draw',
        'game.status.abandoned': 'Abandoned',
        'game.bot.difficulty.easy': 'Novice',
        'game.bot.difficulty.medium': 'Expert',
        'game.bot.difficulty.hard': 'Master',
        'game.timer.label': 'Time remaining',
        'game.timer.currentPlayer': 'Current player',
        'game.turn.label': 'Turn',
        'game.error.title': 'Error',
        'game.error.load': 'Failed to load game',
        'game.error.move': 'Invalid move',
        'game.error.surrender': 'Failed to surrender',
        'game.error.timeout': 'Game did not start automatically. Please refresh the page.',
        'game.error.unknown': 'An error occurred',
        'game.error.websocketConnectionFailed': 'Failed to establish WebSocket connection. Using polling.',
        'game.error.missingToken': 'Missing authentication token',
        'game.error.moveNotAllowed': 'Move not allowed',
        'game.error.cellOccupied': 'Cell is already occupied',
        'game.error.waitingForResponse': 'Waiting for server response...',
        'game.error.websocketReconnecting': 'WebSocket is not connected. Attempting to reconnect...',
        'game.info.title': 'Information',
        'game.info.makingMove': 'Making your move...',
        'game.info.surrendered': 'Game surrendered',
        'game.result.youWon': 'You won!',
        'game.result.youLost': 'You lost',
        'game.result.gameFinished': 'Game finished',
        'game.result.gameDraw': 'Game ended in a draw',
        'game.result.pointsEarned': 'Points earned',
        'game.result.drawPoints': 'Consolation points',
        'auth.login.title': 'Log in',
        'auth.login.email': 'Email',
        'auth.login.password': 'Password',
        'auth.login.submit': 'Log in',
        'auth.login.noAccount': "Don't have an account?",
        'auth.login.registerLink': 'Register',
        'auth.login.or': 'Or',
        'auth.login.playAsGuest': 'play as guest',
        'auth.login.success.title': 'Success',
        'auth.login.success.detail': 'Successfully logged in',
        'auth.login.error.title': 'Login error',
        'auth.login.error.generic': 'An error occurred during login',
        'auth.login.error.invalidCredentials': 'Invalid email or password',
        'auth.login.error.userNotFound': 'User not found',
        'auth.login.validation.required': 'This field is required',
        'auth.login.validation.email': 'Invalid email format',
        'auth.login.validation.minLength': 'Minimum length: {min} characters',
        'auth.login.togglePassword': 'Show/hide password',
        'auth.register.title': 'Register',
        'auth.register.username': 'Username',
        'auth.register.email': 'Email',
        'auth.register.password': 'Password',
        'auth.register.confirmPassword': 'Confirm password',
        'auth.register.submit': 'Register',
        'auth.register.hasAccount': 'Already have an account?',
        'auth.register.loginLink': 'Log in',
        'auth.register.or': 'Or',
        'auth.register.playAsGuest': 'play as guest',
        'auth.register.success.title': 'Success',
        'auth.register.success.detail': 'Account created successfully',
        'auth.register.error.title': 'Registration error',
        'auth.register.error.generic': 'An error occurred during registration',
        'auth.register.error.usernameExists': 'Username already exists',
        'auth.register.error.emailExists': 'Email already exists',
        'auth.register.error.conflict': 'Username or email already exists',
        'auth.register.error.validation': 'Invalid data. Please check the form.',
        'auth.register.validation.required': 'This field is required',
        'auth.register.validation.email': 'Invalid email format',
        'auth.register.validation.minLength': 'Minimum length: {min} characters',
        'auth.register.validation.maxLength': 'Maximum length: {max} characters',
        'auth.register.validation.usernamePattern': 'Username can only contain letters, numbers and underscores',
        'auth.register.validation.passwordMismatch': 'Passwords do not match',
        'auth.register.togglePassword': 'Show/hide password',
        'auth.register.avatar': 'Select Avatar',
        'leaderboard.title': 'Player Rankings',
        'leaderboard.subtitle': 'Global ranking of the best players',
        'leaderboard.table.position': 'Position',
        'leaderboard.table.username': 'Username',
        'leaderboard.table.points': 'Points',
        'leaderboard.table.gamesPlayed': 'Games Played',
        'leaderboard.table.gamesWon': 'Games Won',
        'leaderboard.table.actions': 'Actions',
        'leaderboard.table.empty': 'No players found',
        'leaderboard.challenge.button': 'Challenge',
        'leaderboard.challenge.success.title': 'Success',
        'leaderboard.challenge.success.detail': 'Challenge has been sent',
        'leaderboard.challenge.error.title': 'Error',
        'leaderboard.challenge.error.generic': 'Failed to challenge player',
        'leaderboard.challenge.error.notFound': 'Player not found',
        'leaderboard.challenge.error.unavailable': 'Player is unavailable or already in a game',
        'leaderboard.error.title': 'Error',
        'leaderboard.error.load': 'Failed to load ranking',
        'leaderboard.userRank.title': 'Your Ranking',
        'leaderboard.userRank.points': 'Points',
        'leaderboard.userRank.gamesPlayed': 'Games Played',
        'leaderboard.userRank.gamesWon': 'Games Won',
        'leaderboard.userRank.showPlayersAround': 'Show players around me',
        'leaderboard.playersAround.title': 'Players Around You',
        'leaderboard.playersAround.loading': 'Loading players...',
        'leaderboard.playersAround.empty': 'No players found around your position',
        'leaderboard.playersAround.points': 'points',
        'matchmaking.title': 'Searching for opponent...',
        'matchmaking.searching': 'Searching for opponent...',
        'matchmaking.boardSize': 'Board size',
        'matchmaking.estimatedWaitTime': 'Estimated wait time',
        'matchmaking.seconds': 'seconds',
        'matchmaking.cancel': 'Cancel',
        'matchmaking.cancelled.title': 'Cancelled',
        'matchmaking.cancelled.detail': 'Left matchmaking queue',
        'matchmaking.error.title': 'Error',
        'matchmaking.error.detail': 'An error occurred during matchmaking',
        'matchmaking.error.auth': 'Authentication required. Please log in.',
        'matchmaking.error.alreadyInQueue': 'You are already in the matchmaking queue',
        'matchmaking.error.status': 'Error',
        'queue.title': 'Matchmaking Queue',
        'queue.subtitle': 'Find and join games with other players',
        'queue.allSizes': 'All sizes',
        'queue.totalPlayers': 'Total players',
        'queue.empty': 'No players in queue',
        'queue.matchedWith': 'Matched with',
        'queue.status.waiting': 'Waiting',
        'queue.status.matched': 'Matched',
        'queue.status.playing': 'Playing',
        'queue.boardSize': 'Board size',
        'queue.playing': 'Playing game',
        'queue.join': 'Join game',
        'queue.join.success.title': 'Success',
        'queue.join.success.detail': 'Successfully joined the game',
        'queue.join.error.title': 'Error',
        'queue.join.error.detail': 'Failed to join the game',
        'queue.join.error.ownGame': 'You cannot join your own game',
        'queue.join.error.unavailable': 'This player is currently unavailable (in a game or in queue)',
        'queue.error.title': 'Error',
        'queue.error.detail': 'Failed to load queue status',
        'queue.table.username': 'Username',
        'queue.table.status': 'Status',
        'queue.table.boardSize': 'Board Size',
        'queue.table.details': 'Details',
        'queue.table.actions': 'Actions',
        'profile.title': 'User Profile',
        'profile.info.title': 'Profile Information',
        'profile.username': 'Username',
        'profile.email': 'Email',
        'profile.status': 'Status',
        'profile.guest': 'Guest',
        'profile.guest.info': 'As a guest, your statistics are not saved, you will not be visible in rankings, and you cannot participate in PvP games.',
        'profile.registered': 'Registered',
        'profile.edit': 'Edit',
        'profile.stats.title': 'Statistics',
        'profile.stats.points': 'Points',
        'profile.stats.gamesPlayed': 'Games Played',
        'profile.stats.gamesWon': 'Games Won',
        'profile.stats.winRate': 'Win Rate',
        'profile.ranking.position': 'Ranking Position',
        'profile.lastGame.title': 'Last Game',
        'profile.lastGame.type': 'Type',
        'profile.lastGame.opponent': 'Opponent',
        'profile.lastGame.status': 'Status',
        'profile.lastGame.lastMove': 'Last Move',
        'profile.lastGame.continue': 'Continue Game',
        'profile.registerEncouragement.title': 'Want to track your progress?',
        'profile.registerEncouragement.description': 'Create an account to save your games, earn ranking points, and unlock advanced features.',
        'profile.registerButton': 'Register',
        'profile.loading': 'Loading profile...',
        'profile.update.success': 'Success',
        'profile.update.successDetail': 'Username has been updated',
        'profile.update.error': 'Failed to update username',
        'profile.update.errorSummary': 'Error',
        'profile.update.conflict': 'Username already exists',
        'profile.update.forbidden': 'You do not have permission to update this profile',
        'profile.update.notFound': 'User not found',
        'profile.update.unauthorized': 'Session expired. Please log in again',
        'profile.avatar.selectTitle': 'Select Avatar',
        'profile.avatar.change': 'Change Avatar',
        'profile.avatar.edit': 'Edit Avatar',
        'profile.avatar.updateSuccess': 'Avatar has been updated',
        'profile.avatar.clickToEdit': 'Click to edit avatar',
        'common.cancel': 'Cancel',
        'common.save': 'Save',
        'profile.edit.title': 'Edit Username',
        'profile.edit.cancel': 'Cancel',
        'profile.edit.save': 'Save',
        'profile.edit.username.placeholder': 'Enter new username',
        'profile.edit.username.required': 'Username is required',
        'profile.edit.username.minLength': 'Username must be at least 3 characters',
        'profile.edit.username.maxLength': 'Username must be at most 50 characters',
        'profile.edit.username.pattern': 'Username can only contain letters, numbers, underscores and hyphens',
        'game.type.vsBot': 'vs Bot',
      },
      pl: {
        'home.title': 'World at War: Strategia Turowa',
        'home.subtitle': 'Rywalizuj z botem AI lub wyzwij innych graczy w czasie rzeczywistym',
        'home.status.guest': 'Sesja gościa',
        'home.status.registered': 'Miło Cię widzieć ponownie',
        'home.banner.caption': 'Kontynuuj trwającą bitwę',
        'home.banner.gameType.vsBot': 'Gra przeciwko AI',
        'home.banner.gameType.pvp': 'Mecz PvP',
        'home.banner.difficulty.easy': 'Nowicjusz',
        'home.banner.difficulty.medium': 'Ekspert',
        'home.banner.difficulty.hard': 'Mistrz',
        'home.banner.status.waiting': 'Oczekuje',
        'home.banner.status.inProgress': 'W toku',
        'home.banner.status.finished': 'Zakończona',
        'home.banner.status.abandoned': 'Porzucona',
        'home.banner.status.draw': 'Remis',
        'home.banner.lastActivity': 'Ostatnia aktywność',
        'home.banner.boardSize': 'Rozmiar planszy',
        'home.banner.moves': 'Liczba ruchów',
        'home.banner.continue': 'Kontynuuj grę',
        'home.hero.cta.matchmaking': 'Rozpocznij matchmaking PvP',
        'home.hero.cta.bot': 'Walcz z AI',
        'home.stats.points': 'Punkty',
        'home.stats.played': 'Rozegrane gry',
        'home.stats.won': 'Wygrane gry',
        'home.menu.game': 'Gra',
        'home.menu.matchmaking': 'Lobby',
        'home.menu.ranking': 'Ranking',
        'home.menu.login': 'Logowanie',
        'home.menu.theme': 'Motyw',
        'home.menu.language': 'Język',
        'settings.audio.open': 'Ustawienia dźwięku',
        'settings.audio.title': 'Ustawienia dźwięku',
        'settings.audio.music': 'Muzyka w tle',
        'settings.audio.musicDescription': 'Odtwarzaj ambientową muzykę podczas rozgrywek.',
        'settings.audio.clickSound': 'Dźwięk kliknięć',
        'settings.audio.clickSoundDescription': 'Odtwarzaj delikatny dźwięk przy naciskaniu przycisków.',
        'settings.audio.enabled': 'Włączone',
        'settings.audio.disabled': 'Wyłączone',
        'home.gameModes.sectionTitle': 'Wybierz swoją misję',
        'home.gameModes.sectionSubtitle':
          'Wybierz sposób rozpoczęcia: błyskawiczna potyczka, strategiczny pojedynek z AI lub mecz PvP.',
        'home.gameModes.guest.title': 'Graj jako gość',
        'home.gameModes.guest.description':
          'Utwórz natychmiastową sesję gościa i wskocz do akcji bez logowania.',
        'home.gameModes.bot.title': 'Walcz z AI',
        'home.gameModes.bot.description':
          'Szlifuj taktykę przeciw adaptacyjnym botom na wielu poziomach trudności.',
        'home.gameModes.pvp.title': 'Matchmaking PvP',
        'home.gameModes.pvp.description':
          'Dołącz do globalnej kolejki i zmierz się z prawdziwymi dowódcami w meczach rankingowych.',
        'home.gameModes.access.available': 'Dostępny',
        'home.gameModes.access.unavailable': 'Niedostępny',
        'home.gameModes.select': 'Wybierz',
        'home.gameModes.selectAria': 'Wybierz tryb gry',
        'home.authSection.title': 'Śledź każde zwycięstwo',
        'home.authSection.description':
          'Załóż konto, aby zapisywać postępy, zdobywać punkty rankingowe i odblokować zaawansowane funkcje.',
        'home.authSection.login': 'Zaloguj się',
        'home.authSection.register': 'Zarejestruj się',
        'home.error.title': 'Coś poszło nie tak',
        'home.error.guestSession': 'Nie udało się utworzyć sesji gościa. Spróbuj ponownie za chwilę.',
        'home.error.navigation': 'Nie udało się przejść do wybranego widoku.',
        'home.error.savedGame': 'Nie udało się pobrać ostatniej gry. Możesz rozpocząć nową rozgrywkę.',
        'home.error.connection': 'Nie można połączyć się z serwerem. Sprawdź, czy backend jest uruchomiony i spróbuj ponownie.',
        'home.hero.title': 'Rozpocznij misję',
        'home.hero.description': 'Wybierz sposób gry: szybka sesja gościa albo pełne konto z zapisem postępów.',
        'home.hero.title.loggedIn': 'Witaj ponownie',
        'home.hero.description.loggedIn': 'Rozpocznij nową grę lub kontynuuj trwającą rozgrywkę.',
        'home.hero.guestButton': 'Graj jako gość',
        'home.hero.loginButton': 'Zaloguj się i graj',
        'home.hero.registerButton': 'Stwórz nowe konto',
        'home.hero.newGameButton': 'Nowa gra',
        'home.hero.continueGameButton': 'Kontynuuj grę',
        'home.hero.logoutButton': 'Wyloguj się',
        'home.gameOptions.title': 'Wybierz opcje gry',
        'home.gameOptions.modeTitle': 'Tryb gry',
        'home.gameOptions.boardSizeTitle': 'Rozmiar planszy',
        'home.gameOptions.cancel': 'Anuluj',
        'home.gameOptions.start': 'Rozpocznij grę',
        'home.gameMode.easy': 'vs Nowicjusz',
        'home.gameMode.medium': 'vs Ekspert',
        'home.gameMode.hard': 'vs Mistrz',
        'home.gameMode.pvp': 'PvP',
        'home.boardSize.3x3': '3x3',
        'home.boardSize.4x4': '4x4',
        'home.boardSize.5x5': '5x5',
        'game.title.bot': 'Gra z botem',
        'game.title.pvp': 'Gra PvP',
        'game.action.surrender': 'Poddaj się',
        'game.meta.status': 'Status',
        'game.meta.turn': 'Tura',
        'game.meta.time': 'Czas',
        'game.info.type': 'Typ',
        'game.info.opponent': 'Przeciwnik',
        'game.info.status': 'Status',
        'game.info.currentPlayer': 'Aktualny gracz',
        'game.info.moves': 'Ruchy',
        'game.type.bot': 'vs Bot',
        'game.type.pvp': 'PvP',
        'game.pvp.points': 'Punkty do zdobycia',
        'game.status.waiting': 'Oczekiwanie',
        'game.status.in_progress': 'W toku',
        'game.status.finished': 'Zakończona',
        'game.status.draw': 'Remis',
        'game.status.abandoned': 'Porzucona',
        'game.bot.difficulty.easy': 'Nowicjusz',
        'game.bot.difficulty.medium': 'Ekspert',
        'game.bot.difficulty.hard': 'Mistrz',
        'game.timer.label': 'Pozostały czas',
        'game.timer.currentPlayer': 'Aktualny gracz',
        'game.turn.label': 'Tura',
        'game.error.title': 'Błąd',
        'game.error.load': 'Nie udało się załadować gry',
        'game.error.move': 'Nieprawidłowy ruch',
        'game.error.surrender': 'Nie udało się poddać gry',
        'game.error.timeout': 'Gra nie rozpoczęła się automatycznie. Odśwież stronę.',
        'game.error.unknown': 'Wystąpił błąd',
        'game.error.websocketConnectionFailed': 'Nie udało się nawiązać połączenia WebSocket. Używam polling.',
        'game.error.missingToken': 'Brak tokenu uwierzytelniającego',
        'game.error.moveNotAllowed': 'Ruch niedozwolony',
        'game.error.cellOccupied': 'Pole jest już zajęte',
        'game.error.waitingForResponse': 'Czekam na odpowiedź z serwera...',
        'game.error.websocketReconnecting': 'WebSocket nie jest połączony. Próba ponownego połączenia...',
        'game.info.title': 'Informacja',
        'game.info.makingMove': 'Wykonywanie ruchu...',
        'game.info.surrendered': 'Gra poddana',
        'game.result.youWon': 'Wygrałeś!',
        'game.result.youLost': 'Przegrałeś',
        'game.result.gameFinished': 'Gra zakończona',
        'game.result.gameDraw': 'Gra zakończona remisem',
        'game.result.pointsEarned': 'Zdobyte punkty',
        'game.result.drawPoints': 'Punkty pocieszenia',
        'auth.login.title': 'Logowanie',
        'auth.login.email': 'Email',
        'auth.login.password': 'Hasło',
        'auth.login.submit': 'Zaloguj się',
        'auth.login.noAccount': 'Nie masz konta?',
        'auth.login.registerLink': 'Zarejestruj się',
        'auth.login.or': 'Lub',
        'auth.login.playAsGuest': 'graj jako gość',
        'auth.login.success.title': 'Sukces',
        'auth.login.success.detail': 'Zalogowano pomyślnie',
        'auth.login.error.title': 'Błąd logowania',
        'auth.login.error.generic': 'Wystąpił błąd podczas logowania',
        'auth.login.error.invalidCredentials': 'Nieprawidłowy email lub hasło',
        'auth.login.error.userNotFound': 'Użytkownik nie został znaleziony',
        'auth.login.validation.required': 'To pole jest wymagane',
        'auth.login.validation.email': 'Nieprawidłowy format email',
        'auth.login.validation.minLength': 'Minimalna długość: {min} znaków',
        'auth.login.togglePassword': 'Pokaż/ukryj hasło',
        'auth.register.title': 'Rejestracja',
        'auth.register.username': 'Nazwa użytkownika',
        'auth.register.email': 'Email',
        'auth.register.password': 'Hasło',
        'auth.register.confirmPassword': 'Potwierdzenie hasła',
        'auth.register.submit': 'Zarejestruj się',
        'auth.register.hasAccount': 'Masz już konto?',
        'auth.register.loginLink': 'Zaloguj się',
        'auth.register.or': 'Lub',
        'auth.register.playAsGuest': 'graj jako gość',
        'auth.register.success.title': 'Sukces',
        'auth.register.success.detail': 'Konto zostało utworzone pomyślnie',
        'auth.register.error.title': 'Błąd rejestracji',
        'auth.register.error.generic': 'Wystąpił błąd podczas rejestracji',
        'auth.register.error.usernameExists': 'Nazwa użytkownika już istnieje',
        'auth.register.error.emailExists': 'Email już istnieje',
        'auth.register.error.conflict': 'Nazwa użytkownika lub email już istnieje',
        'auth.register.error.validation': 'Nieprawidłowe dane. Sprawdź formularz.',
        'auth.register.validation.required': 'To pole jest wymagane',
        'auth.register.validation.email': 'Nieprawidłowy format email',
        'auth.register.validation.minLength': 'Minimalna długość: {min} znaków',
        'auth.register.validation.maxLength': 'Maksymalna długość: {max} znaków',
        'auth.register.validation.usernamePattern': 'Nazwa użytkownika może zawierać tylko litery, cyfry i podkreślniki',
        'auth.register.validation.passwordMismatch': 'Hasła nie są zgodne',
        'auth.register.togglePassword': 'Pokaż/ukryj hasło',
        'auth.register.avatar': 'Wybierz Avatar',
        'leaderboard.title': 'Ranking graczy',
        'leaderboard.subtitle': 'Globalny ranking najlepszych graczy',
        'leaderboard.table.position': 'Pozycja',
        'leaderboard.table.username': 'Nazwa użytkownika',
        'leaderboard.table.points': 'Punkty',
        'leaderboard.table.gamesPlayed': 'Rozegrane gry',
        'leaderboard.table.gamesWon': 'Wygrane gry',
        'leaderboard.table.actions': 'Akcje',
        'leaderboard.table.empty': 'Nie znaleziono graczy',
        'leaderboard.challenge.button': 'Wyzwij',
        'leaderboard.challenge.success.title': 'Sukces',
        'leaderboard.challenge.success.detail': 'Wyzwanie zostało wysłane',
        'leaderboard.challenge.error.title': 'Błąd',
        'leaderboard.challenge.error.generic': 'Nie udało się wyzwać gracza',
        'leaderboard.challenge.error.notFound': 'Gracz nie został znaleziony',
        'leaderboard.challenge.error.unavailable': 'Gracz jest niedostępny lub już w grze',
        'leaderboard.error.title': 'Błąd',
        'leaderboard.error.load': 'Nie udało się załadować rankingu',
        'leaderboard.userRank.title': 'Twój ranking',
        'leaderboard.userRank.points': 'Punkty',
        'leaderboard.userRank.gamesPlayed': 'Rozegrane gry',
        'leaderboard.userRank.gamesWon': 'Wygrane gry',
        'leaderboard.userRank.showPlayersAround': 'Pokaż graczy wokół mnie',
        'leaderboard.playersAround.title': 'Gracze wokół Ciebie',
        'leaderboard.playersAround.loading': 'Ładowanie graczy...',
        'leaderboard.playersAround.empty': 'Nie znaleziono graczy wokół Twojej pozycji',
        'leaderboard.playersAround.points': 'punktów',
        'matchmaking.title': 'Szukanie przeciwnika...',
        'matchmaking.searching': 'Szukanie przeciwnika...',
        'matchmaking.boardSize': 'Rozmiar planszy',
        'matchmaking.estimatedWaitTime': 'Szacowany czas oczekiwania',
        'matchmaking.seconds': 'sekund',
        'matchmaking.cancel': 'Anuluj',
        'matchmaking.cancelled.title': 'Anulowano',
        'matchmaking.cancelled.detail': 'Opuszczono kolejkę matchmakingu',
        'matchmaking.error.title': 'Błąd',
        'matchmaking.error.detail': 'Wystąpił błąd podczas matchmakingu',
        'matchmaking.error.auth': 'Wymagane uwierzytelnienie. Zaloguj się.',
        'matchmaking.error.alreadyInQueue': 'Jesteś już w kolejce matchmakingu',
        'matchmaking.error.status': 'Błąd',
        'queue.title': 'Kolejka matchmakingu',
        'queue.subtitle': 'Znajdź i dołącz do gier z innymi graczami',
        'queue.allSizes': 'Wszystkie rozmiary',
        'queue.totalPlayers': 'Łącznie graczy',
        'queue.empty': 'Brak graczy w kolejce',
        'queue.matchedWith': 'Sparowany z',
        'queue.status.waiting': 'Oczekiwanie',
        'queue.status.matched': 'Sparowany',
        'queue.status.playing': 'W grze',
        'queue.boardSize': 'Rozmiar planszy',
        'queue.playing': 'W grze',
        'queue.join': 'Dołącz do gry',
        'queue.join.success.title': 'Sukces',
        'queue.join.success.detail': 'Pomyślnie dołączono do gry',
        'queue.join.error.title': 'Błąd',
        'queue.join.error.detail': 'Nie udało się dołączyć do gry',
        'queue.join.error.ownGame': 'Nie możesz dołączyć do własnej gry',
        'queue.join.error.unavailable': 'Ten gracz jest obecnie niedostępny (w grze lub w kolejce)',
        'queue.error.title': 'Błąd',
        'queue.error.detail': 'Nie udało się załadować statusu kolejki',
        'queue.table.username': 'Nazwa użytkownika',
        'queue.table.status': 'Status',
        'queue.table.boardSize': 'Rozmiar planszy',
        'queue.table.details': 'Szczegóły',
        'queue.table.actions': 'Akcje',
        'profile.title': 'Profil użytkownika',
        'profile.info.title': 'Informacje o profilu',
        'profile.username': 'Nazwa użytkownika',
        'profile.email': 'Email',
        'profile.status': 'Status',
        'profile.guest': 'Gość',
        'profile.guest.info': 'Jako gość, Twoje statystyki nie są zapisywane, nie będziesz widoczny w rankingach i nie możesz uczestniczyć w grach PvP.',
        'profile.registered': 'Zarejestrowany',
        'profile.edit': 'Edytuj',
        'profile.stats.title': 'Statystyki',
        'profile.stats.points': 'Punkty',
        'profile.stats.gamesPlayed': 'Rozegrane gry',
        'profile.stats.gamesWon': 'Wygrane gry',
        'profile.stats.winRate': 'Współczynnik wygranych',
        'profile.ranking.position': 'Pozycja w rankingu',
        'profile.lastGame.title': 'Ostatnia gra',
        'profile.lastGame.type': 'Typ',
        'profile.lastGame.opponent': 'Przeciwnik',
        'profile.lastGame.status': 'Status',
        'profile.lastGame.lastMove': 'Ostatni ruch',
        'profile.lastGame.continue': 'Kontynuuj grę',
        'profile.registerEncouragement.title': 'Chcesz śledzić swoje postępy?',
        'profile.registerEncouragement.description': 'Załóż konto, aby zapisywać swoje gry, zdobywać punkty rankingowe i odblokować zaawansowane funkcje.',
        'profile.registerButton': 'Zarejestruj się',
        'profile.loading': 'Ładowanie profilu...',
        'profile.update.success': 'Sukces',
        'profile.update.successDetail': 'Nazwa użytkownika została zaktualizowana',
        'profile.update.error': 'Nie udało się zaktualizować nazwy użytkownika',
        'profile.update.errorSummary': 'Błąd',
        'profile.update.conflict': 'Nazwa użytkownika już istnieje',
        'profile.update.forbidden': 'Nie masz uprawnień do aktualizacji tego profilu',
        'profile.update.notFound': 'Użytkownik nie znaleziony',
        'profile.update.unauthorized': 'Sesja wygasła. Zaloguj się ponownie',
        'profile.avatar.selectTitle': 'Wybierz Avatar',
        'profile.avatar.change': 'Zmień Avatar',
        'profile.avatar.edit': 'Edytuj Avatar',
        'profile.avatar.updateSuccess': 'Avatar został zaktualizowany',
        'profile.avatar.clickToEdit': 'Kliknij, aby edytować avatar',
        'common.cancel': 'Anuluj',
        'common.save': 'Zapisz',
        'profile.edit.title': 'Edytuj nazwę użytkownika',
        'profile.edit.cancel': 'Anuluj',
        'profile.edit.save': 'Zapisz',
        'profile.edit.username.placeholder': 'Wprowadź nową nazwę użytkownika',
        'profile.edit.username.required': 'Nazwa użytkownika jest wymagana',
        'profile.edit.username.minLength': 'Nazwa użytkownika musi mieć co najmniej 3 znaki',
        'profile.edit.username.maxLength': 'Nazwa użytkownika może mieć maksymalnie 50 znaków',
        'profile.edit.username.pattern': 'Nazwa użytkownika może zawierać tylko litery, cyfry, podkreślniki i myślniki',
        'game.type.vsBot': 'vs Bot',
      },
    };

  readonly languageChanges$ = toObservable(this.languageSignal);
  readonly currentLanguage = computed(() => this.languageSignal());

  setLanguage(language: SupportedLanguage): void {
    this.languageSignal.set(language);
  }

  translate(key: string, params?: Record<string, string | number>): string {
    const language = this.languageSignal();
    const dictionary = this.translations[language];
    let translation = dictionary[key] ?? key;

    if (params) {
      Object.keys(params).forEach((paramKey) => {
        translation = translation.replace(`{${paramKey}}`, String(params[paramKey]));
      });
    }

    return translation;
  }
}

